
export enum ScreenName {
  WELCOME = 'WELCOME',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  OTP = 'OTP',
  CREATE_PASSWORD = 'CREATE_PASSWORD',
  HOME = 'HOME',
  
  // Pump Flow (User)
  SCAN_QR = 'SCAN_QR',
  CONFIRM_PUMP = 'CONFIRM_PUMP',
  SELECT_MODE = 'SELECT_MODE',
  INPUT_AMOUNT = 'INPUT_AMOUNT',
  PUMPING = 'PUMPING',
  SUCCESS = 'SUCCESS',
  
  // License Plate Flow (AI)
  LICENSE_REGISTER = 'LICENSE_REGISTER', // Màn hình đăng ký xe
  LICENSE_SCAN = 'LICENSE_SCAN',         // Màn hình quét camera AI
  
  // Guest Flow
  GUEST_SCAN = 'GUEST_SCAN',
  GUEST_CONFIRM_PUMP = 'GUEST_CONFIRM_PUMP',
  GUEST_INPUT_AMOUNT = 'GUEST_INPUT_AMOUNT',
  GUEST_INVOICE_INFO = 'GUEST_INVOICE_INFO',
  GUEST_PAYMENT_METHOD = 'GUEST_PAYMENT_METHOD',
  GUEST_PAYMENT_QR = 'GUEST_PAYMENT_QR', 
  GUEST_PAYMENT_BANK_LIST = 'GUEST_PAYMENT_BANK_LIST', 
  GUEST_PAYMENT_BANK_DETAIL = 'GUEST_PAYMENT_BANK_DETAIL', 
  GUEST_PAYMENT_WALLET = 'GUEST_PAYMENT_WALLET', 
  GUEST_PAYMENT_PROCESS = 'GUEST_PAYMENT_PROCESS', 
  GUEST_PUMP_READY = 'GUEST_PUMP_READY',
  GUEST_PUMPING = 'GUEST_PUMPING',
  GUEST_PUMP_COMPLETE = 'GUEST_PUMP_COMPLETE', 
  GUEST_TRANSACTION_COMPLETE = 'GUEST_TRANSACTION_COMPLETE', 
  GUEST_COMPLETE = 'GUEST_COMPLETE',
  GUEST_REFUND = 'GUEST_REFUND',

  // Wallet
  WALLET_TOPUP = 'WALLET_TOPUP',
  WALLET_WITHDRAW = 'WALLET_WITHDRAW',
  WALLET_LINK_BANK = 'WALLET_LINK_BANK',
  WALLET = 'WALLET',
  
  // Activity
  ACTIVITY = 'ACTIVITY',
  ACTIVITY_DETAIL = 'ACTIVITY_DETAIL',
  
  // Profile
  PROFILE = 'PROFILE',
  PROFILE_EDIT = 'PROFILE_EDIT',
  PROFILE_INVOICE = 'PROFILE_INVOICE',
  PROFILE_INVOICE_EDIT = 'PROFILE_INVOICE_EDIT',
  MY_VEHICLES = 'MY_VEHICLES',
  MY_VEHICLE_DETAIL = 'MY_VEHICLE_DETAIL',
  MY_VEHICLE_ADD = 'MY_VEHICLE_ADD'
}

export interface Transaction {
  id: string;
  amount: number;
  liters: number;
  date: string;
  station: string;
  status: 'success' | 'failed' | 'pending';
}

export enum PumpMode {
  FULL = 'FULL',
  AMOUNT = 'AMOUNT',
  LITERS = 'LITERS'
}